In [116]:
import numpy as np
import pandas as pd

df = pd.read_csv("Real estate.csv")
y = df['house price of unit area']
df.drop('No', inplace=True, axis=1)
df.drop('transaction date', inplace=True, axis=1)
print(df.head())

   house age  distance to the nearest MRT station  \
0       32.0                             84.87882   
1       19.5                            306.59470   
2       13.3                            561.98450   
3       13.3                            561.98450   
4        5.0                            390.56840   

   number of convenience stores  latitude  longitude  house price of unit area  
0                            10  24.98298  121.54024                      37.9  
1                             9  24.98034  121.53951                      42.2  
2                             5  24.98746  121.54391                      47.3  
3                             5  24.98746  121.54391                      54.8  
4                             5  24.97937  121.54245                      43.1  


In [117]:
inputs = df.iloc[:100,:-1].values
output = df.iloc[:100,-1:].values

In [118]:
import torch
import math

In [119]:
inp = torch.from_numpy(inputs).float()
oup = torch.from_numpy(output).float()

In [120]:
import torch.nn as nn

In [121]:
from torch.utils.data import TensorDataset, DataLoader
tensor_dataset = TensorDataset(inp,oup)
batch_size = 5

In [122]:
train = DataLoader(tensor_dataset, batch_size, shuffle=True)

In [123]:
for a, b in train:
    print(a)
    print(b)
    break

tensor([[4.0100e+01, 1.2374e+02, 8.0000e+00, 2.4976e+01, 1.2154e+02],
        [1.0100e+01, 2.7917e+02, 7.0000e+00, 2.4975e+01, 1.2155e+02],
        [1.0400e+01, 2.7645e+02, 5.0000e+00, 2.4956e+01, 1.2154e+02],
        [1.6900e+01, 4.0666e+03, 0.0000e+00, 2.4943e+01, 1.2150e+02],
        [1.7200e+01, 2.1759e+03, 3.0000e+00, 2.4963e+01, 1.2151e+02]])
tensor([[44.3000],
        [47.9000],
        [33.6000],
        [18.3000],
        [27.7000]])


In [124]:
model = nn.Linear(5,1)

In [125]:
list(model.parameters())

[Parameter containing:
 tensor([[ 1.6293e-01,  4.1864e-01,  4.2117e-01,  1.8260e-04, -4.4175e-01]],
        requires_grad=True), Parameter containing:
 tensor([0.3211], requires_grad=True)]

In [126]:
import torch.nn.functional as F
loss_fn = F.mse_loss

In [127]:
opt = torch.optim.SGD(model.parameters(), lr=0.000000001)

In [128]:
# MSE loss
def mse(t1, t2):
    print("--------------------------\n")
    print(t1)
    print("\n\n")
    print(t2)
    print("--------------------------\n")
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [135]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred,yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
        
        # Print the progress
        if (epoch+1) % 100 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [136]:
fit(10000, model, loss_fn, opt, train)

Epoch [100/10000], Loss: 97.4431
Epoch [200/10000], Loss: 127.6807
Epoch [300/10000], Loss: 127.0707
Epoch [400/10000], Loss: 31.2523
Epoch [500/10000], Loss: 61.4407
Epoch [600/10000], Loss: 40.2186
Epoch [700/10000], Loss: 185.8433
Epoch [800/10000], Loss: 112.8724
Epoch [900/10000], Loss: 210.7195
Epoch [1000/10000], Loss: 74.4607
Epoch [1100/10000], Loss: 128.5415
Epoch [1200/10000], Loss: 169.8896
Epoch [1300/10000], Loss: 240.4256
Epoch [1400/10000], Loss: 97.1384
Epoch [1500/10000], Loss: 111.2803
Epoch [1600/10000], Loss: 109.8444
Epoch [1700/10000], Loss: 112.2238
Epoch [1800/10000], Loss: 121.4437
Epoch [1900/10000], Loss: 145.4031
Epoch [2000/10000], Loss: 95.0756
Epoch [2100/10000], Loss: 105.7113
Epoch [2200/10000], Loss: 62.4106
Epoch [2300/10000], Loss: 71.5407
Epoch [2400/10000], Loss: 51.8589
Epoch [2500/10000], Loss: 49.7936
Epoch [2600/10000], Loss: 70.1387
Epoch [2700/10000], Loss: 221.2426
Epoch [2800/10000], Loss: 99.1553
Epoch [2900/10000], Loss: 135.2515
Epoch [

In [137]:
model(torch.tensor([[10., 101., 12., 30., 122.]]))

tensor([[48.1908]], grad_fn=<AddmmBackward>)